name: Setup Lib
description: Setup & Install

inputs:
  node-version:
    description: Version of Node to use
    default: 22.x

runs:
  using: composite
  steps:
    - name: setup Node
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - uses: pnpm/action-setup@v4
      with:
        standalone: true
        dest: ~/setup-pnpm
    - name: Install deps
      run: pnpm install --frozen-lockfile
      shell: bash
