name: CI
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  lint:
    name: run lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-repo
      - run: pnpm run lint
  format:
    name: run format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-repo
      - run: pnpm run format
  test:
    timeout-minutes: 60
    name: run e2e test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    steps:
      - uses: pnpm/action-setup@v4
        with:
          version: 9.13.2
          run_install: false
          standalone: true
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install deps
        run: pnpm install
      - name: Build lib vite multiple assets
        run: npx turbo run build --filter=vite-multiple-assets
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Run Test load multiple assets by React App
        run: pnpm run e2e react
      #      - name: Run Test load multiple assets by Astro App
      #        run: pnpm run e2e astro
      #      - name: Run Test load multiple assets by Vue3 App
      #        run: pnpm run e2e vue3
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
